local_backend: true

backend:
  name: github
  repo: alexander-entin/astro-blog-example
  branch: main
  use_graphql: true
  site_domain: astro-als.pages.dev
  base_url: https://astro-als.pages.dev
  auth_endpoint: oauth

media_folder: src/assets/images
public_folder: "@assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/collections/posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path_date_field: pubDatetime
    fields:
      - { name: author, label: Author, widget: string }
      - { name: pubDatetime, label: Published, widget: datetime, required: false }
      - { name: modDatetime, label: Modified, widget: datetime, required: false }
      - { name: title, label: Title, widget: string }
      - { name: ogImage, label: OgImage, widget: string, required: false }
      - { name: slug, label: Slug, widget: string }
      - { name: featured, label: Featured, widget: boolean, default: false }
      - { name: draft, label: Draft, widget: boolean, default: false }
      #- { name: tags, label: Tags, widget: string, list: true }
      - { name: description, label: Description, widget: string }
      - { name: body, label: Body, widget: markdown }
